### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by Akash-1gif** [Akash-1gif/Web-Scraper-for-images#2]
Need a proper user interface for this project. The current UI is made using Bootstrap (only Bootstrap). Make the UI better using CSS

**Comment by shaypower** [comment]
hey! ill give a crack at it

**Comment by Akash-1gif** [comment]
> hey! ill give a crack at it

Sure, give it a try. If you need any help, you can contact me here.

**Comment by shaypower** [comment]
i am planning on adding a incrementing counter showing how many images are downloaded and the total, is that alright? i have also tried to make it look abit better but due to its simplicity its hard ^^

**Comment by Akash-1gif** [comment]
> i am planning on adding a incrementing counter showing how many images are downloaded and the total, is that alright? i have also tried to make it look abit better but due to its simplicity its hard ^^

sure you can do that

**Comment by shaypower** [comment]
sent a merge request
